# Generated by Django 5.1.5 on 2025-02-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('biografia', models.CharField(blank=True, max_length=400)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='LibrosApp/autores')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'insertar_autor',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=20)),
                ('sub_genero_a', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_genero_b', models.CharField(blank=True, max_length=20, null=True)),
                ('editorial', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('resumen', models.TextField()),
                ('puntuacion_choice', models.IntegerField(choices=[(1, '1 Estrella'), (2, '2 Estrella'), (3, '3 Estrella'), (4, '4 Estrella'), (5, '5 Estrella')], default=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='LibrosApp/libros')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro', to='LibrosApp.autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'insertar_libro',
                'ordering': ['fecha_publicacion'],
            },
        ),
    ]
