# Generated by Django 5.1.5 on 2025-02-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrosApp', '0002_alter_libro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
