# Generated by Django 5.1.5 on 2025-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrosApp', '0003_alter_autor_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(),
        ),
    ]
