# Generated by Django 5.1.5 on 2025-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrosApp', '0004_alter_autor_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No Ficción'), ('fantasia', 'Fantasía'), ('ciencia_ficcion', 'Ciencia Ficción'), ('biografia', 'Biografía'), ('historia', 'Historia'), ('romance', 'Romance'), ('terror', 'Terror'), ('aventura', 'Aventura'), ('misterio', 'Misterio')], max_length=20),
        ),
    ]
