# Generated by Django 5.1.5 on 2025-02-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrosApp', '0007_alter_libro_genero_alter_libro_sub_genero_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreDirectorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'NombreDirectorio',
                'verbose_name_plural': 'NombreDirectorios',
                'db_table': 'seleccionar_nombre_directorio',
            },
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('novela', 'Novela'), ('ficcion', 'Ficción'), ('no_ficcion', 'No Ficción'), ('fantasia', 'Fantasía'), ('ciencia_ficcion', 'Ciencia Ficción'), ('biografia', 'Biografía'), ('historia', 'Historia'), ('romance', 'Romance'), ('terror', 'Terror'), ('aventura', 'Aventura'), ('misterio', 'Misterio')], max_length=30),
        ),
        migrations.AlterField(
            model_name='libro',
            name='sub_genero_a',
            field=models.CharField(blank=True, choices=[('aventura', 'Aventura'), ('fantasia', 'Fantasía'), ('ficcion', 'Ficción'), ('literatura_fantastica', 'Literatura Fantástica'), ('aventura_fantastica', 'Aventura Fantástica'), ('alta_fantasia', 'Alta Fantasía'), ('drama', 'Drama'), ('accion', 'Acción'), ('thriller', 'Thriller'), ('comedia', 'Comedia'), ('psicologico', 'Psicológico'), ('romance_fantastico', 'Romance Fantástico'), ('ficcion_historica', 'Ficción Histórica'), ('terror_psicologico', 'Terror Psicológico')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='sub_genero_b',
            field=models.CharField(blank=True, choices=[('aventura', 'Aventura'), ('fantasia', 'Fantasía'), ('ficcion', 'Ficción'), ('literatura_fantastica', 'Literatura Fantástica'), ('aventura_fantastica', 'Aventura Fantástica'), ('alta_fantasia', 'Alta Fantasía'), ('drama', 'Drama'), ('accion', 'Acción'), ('thriller', 'Thriller'), ('comedia', 'Comedia'), ('psicologico', 'Psicológico'), ('romance_fantastico', 'Romance Fantástico'), ('ficcion_historica', 'Ficción Histórica'), ('terror_psicologico', 'Terror Psicológico')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='nombre_directorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libro', to='LibrosApp.nombredirectorio'),
        ),
    ]
