# Generated by Django 5.1.5 on 2025-02-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrosApp', '0008_nombredirectorio_alter_libro_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen_background',
            field=models.ImageField(blank=True, null=True, upload_to='Background'),
        ),
    ]
