# Generated by Django 5.1.5 on 2025-02-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrosApp', '0009_libro_imagen_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen_background',
            field=models.ImageField(blank=True, null=True, upload_to='Background/'),
        ),
    ]
